// Generated by CoffeeScript 1.10.0
Site.controller('SearchController', [
  '$scope', 'SearchApi', function($scope, searchApi) {
    $scope.greeting = 'Hello, world';
    $scope.query = '';
    $scope.search = function() {
      return searchApi.get({
        query: $scope.query
      }, function(result) {
        return console.log(result);
      });
    };
    return true;
  }
]);
